name: Firebase Deploy

on:
  push:
    branches: [ release/staging ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Clones this repo
      - uses: actions/checkout@v2
      
      # Creates directory
      - name: Create supreme-pancake dir
        run: |
          mkdir supreme-pancake
          shopt -s extglob
          mv !(supreme-pancake) supreme-pancake
    
      # Clones Firebase Deploy Info
      - name: Clone Juler-Hosting
        run: |
          git clone ${{ secrets.HOSTING_REPO }} host
          cp ./host/.firebaserc .
          cp ./host/firebase.json .
          rm -rf host
      
      # Installs Firebase
      - name: Install Firebase
        run: npm install -g firebase-tools
  
      # Authenticates and then Deploys
      - name: Authenticate with Firebase
        run: |
          echo "$FIREBASE_SA_KEY" > service-account-key.json
          export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/service-account-key.json
          firebase use juler-sites
          firebase deploy --only hosting:supremepancake-beta --non-interactive
        env:
          FIREBASE_SA_KEY: ${{ secrets.FIREBASE_SA_KEY }}
